In [1]:
import numpy as np

### 1.

In [3]:
#Use Naive Gauss Elimination to solve

A = np.array([[4,1,-1],[5,1,2],[6,1,1]],dtype=float)
b= np.array([2,4,6],dtype=float)

#Forward Elimination
#Transform the matrix A into an upper triangular matrix.

n = len(b)
for i in range(n):
    #Make the diagonal element 1
    for j in range(i + 1, n):
        factor = A[j, i] / A[i, i]
        A[j, i:] -= factor * A[i, i:]
        b[j] -= factor * b[i]

#Backward Substitution
x = np.zeros(n)
for i in range(n - 1, -1, -1):
    x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

print(f"Upper Triangular Matrix A:\n{A}\nModified b: {b}\nSolution x: {x}")

Upper Triangular Matrix A:
[[ 4.    1.   -1.  ]
 [ 0.   -0.25  3.25]
 [ 0.    0.   -4.  ]]
Modified b: [2.  1.5 0. ]
Solution x: [ 2. -6. -0.]


### 2.

In [5]:
#Assume that you are using a computer with four significant digits with chopping.
#Use Naïve Gauss elimination method to solve

A = np.array([[4,1,-1],[5,1,2],[6,1,1]],dtype=float)
b= np.array([2,4,6],dtype=float)

def chop(value):
    return np.floor(value * 1e4) / 1e4
#Apply chopping
A = np.vectorize(chop)(A)
b = np.vectorize(chop)(b)

#Naive Gauss Elimination with chopping
n = len(b)
for i in range(n):
    for j in range(i + 1, n):
        factor = chop(A[j, i] / A[i, i])
        A[j, i:] = np.vectorize(chop)(A[j, i:] - factor * A[i, i:])
        b[j] = chop(b[j] - factor * b[i])

#Backward Substitution with chopping
x = np.zeros(n)
for i in range(n - 1, -1, -1):
    x[i] = chop((b[i] - chop(np.dot(A[i, i + 1:], x[i + 1:]))) / A[i, i])

print(f"[A]:\n{A}\n b: {b}\n x: {x}")

[A]:
[[ 4.    1.   -1.  ]
 [ 0.   -0.25  3.25]
 [ 0.    0.   -4.  ]]
 b: [2.  1.5 0. ]
 x: [ 2. -6. -0.]


### 3.

In [7]:
#Find the determinant of [A] using forward elimination step of naïve Gauss elimination method.

A = np.array([[10,-7,0],[-3,2.099,6],[5,-1,5]],dtype=float)

n = len(A)
det = 1  #Initialize determinant

for i in range(n):
    #Multiply by the diagonal element for determinant
    det *= A[i, i]
    for j in range(i + 1, n):
        factor = A[j, i] / A[i, i]
        A[j, i:] -= factor * A[i, i:]

#Determinant is the product of the diagonal elements
det = np.prod(np.diag(A))
print(f"[A]:\n {A}\nDeterminant of [A]: \n{det}")

#det = np.linalg.det(A)
#print(det)

[A]:
 [[ 1.0000e+01 -7.0000e+00  0.0000e+00]
 [ 0.0000e+00 -1.0000e-03  6.0000e+00]
 [ 0.0000e+00  0.0000e+00  1.5005e+04]]
Determinant of [A]: 
-150.04999999999998


### 4.

In [9]:
#At the end of forward elimination steps using naïve Gauss elimination method on the coefficient matrix
#A = np.array([[25,c,1],[64,a,1],[144,b,1]])
#[A] reduces to
B = np.array([[25,5,1],[0,-4.8,-1.56],[0,0,0.7]])
#What is the determinant of A?

#Compute the determinant as the product of diagonal elements
det_A = np.prod(np.diag(B))

print("The determinant of [A] is:", det_A)
#The determinant of [A] after forward elimination using naïve Gauss Elimination = The product of the diagonal elements of the upper triangular matrix of [B].

The determinant of [A] is: -84.0


### 5.

In [11]:
#Using Gaussian elimination with partial pivoting to solve
A = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b = np.array([2, 4, 6], dtype=float)

# Function to perform the Gaussian Elimination with Partial Pivoting
def parpiv(A, b):
    n = len(b)
    
    # Forward elimination with partial pivoting
    for i in range(n):
    # Partial pivoting: 
        #find the maximum element in the current column
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if i != max_row:
            # Swap rows in A and b
            A[[i, max_row]] = A[[max_row, i]]
            b[[i, max_row]] = b[[max_row, i]]
        
        # Eliminate entries below the pivot
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]
    
    # Backward substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]
    
    return x

print("x: ", x)

x:  [ 2. -6. -0.]


### 6.

In [13]:
#Assume that you are using a computer with four significant digits with chopping, use Gaussian elimination with partial pivoting to solve
A = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b = np.array([2, 4, 6], dtype=float)

def chop(value):
    return np.floor(value * 1e4) / 1e4

# Function to perform Gaussian elimination with partial pivoting and chopping
def parpivcho(A, b):
    n = len(b)
    
    # Chop initial values of A and b
    A = np.vectorize(chop)(A)
    b = np.vectorize(chop)(b)
    
    # Forward elimination with partial pivoting
    for i in range(n):
        # Partial pivoting: find the maximum element in the current column
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if i != max_row:
            # Swap rows in A and b
            A[[i, max_row]] = A[[max_row, i]]
            b[[i, max_row]] = b[[max_row, i]]
        
        # Eliminate entries below the pivot
        for j in range(i + 1, n):
            factor = chop(A[j, i] / A[i, i])
            A[j, i:] = np.vectorize(chop)(A[j, i:] - factor * A[i, i:])
            b[j] = chop(b[j] - factor * b[i])
    
    # Backward substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = chop((b[i] - chop(np.dot(A[i, i + 1:], x[i + 1:]))) / A[i, i])
    
    return x

# Define the matrix A and vector b
A = np.array([[4, 1, -1], [5, 1, 2], [6, 1, 1]], dtype=float)
b = np.array([2, 4, 6], dtype=float)

# Solve the system
x_chopped = parpivcho(A, b)

print("x: ", x_chopped)

x:  [ 1.9999e+00 -5.9995e+00 -4.0000e-04]
